### ISSUE TITLE
Kaga knock out inconsistency

### ISSUE THREAD

**Issue by Risu** [BGforgeNet/Fallout2_Restoration_Project#13]
Kaga in the last encounter can be knocked down, but not in the previous ones.
I propose to remove "cannot be knocked down" flags from kaga 1-4 proto files (character is enough irritable as it is and can be killed without knocking down nonetheless).
Modified protos:
[protos.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/3506974/protos.zip)

**Comment by Risu** [comment]
Script gl_k_kagako.int needs to be ditched too.

**Comment by burner1024** [comment]
This is really a judgement call, and I feel bad about it, because it was clearly intended to work this way.
However, my impression is that many people do hate Kaga, and I myself prefer the combat fair, in sense that both PC and enemies are treated equally. And there's no in-game explanation why Kaga wouldn't be knocked down in the first 4 encounters.
So I'm going to add it. Probably also need to add a setting to disable Kaga altogether.
