### ISSUE TITLE
Crash upon using lockpick in the NCR

### ISSUE THREAD

**Issue by Anarcho-Bolshevik** [BGforgeNet/Fallout2_Restoration_Project#151]
### What happened

I used the lockpick skill on a door in the slaver’s house in the NCR, and my game crashed. (The door in question was the one leading to the backroom with the refrigerator.)

### What you expected to happen

Not a big deal, actually, since I misremembered that this door was locked. It’s strange that I can’t lock it, though.

### Screenshot

![crash](https://user-images.githubusercontent.com/51846125/184571274-8804edff-7eac-4cb9-b4e0-bb2709bb09c5.png)

### Savegame

[debug & save.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/9334908/debug.save.zip)

**Comment by NovaRain** [comment]
The check conditions at line 119 & 162 in [`sivdor.ssl`](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/scripts_src/ncr/sivdor.ssl) for `use_skill_on_p_proc` and `use_obj_on_p_proc` are set up incorrectly, so the script still passes a null pointer (since Vortis is dead) to `add_timer_event` script function.

The condition should be a simple `(i_vortis_obj > 0)`.
