### ISSUE TITLE
can't shutdown turrets in fight with Frank (can only make them attack him)

### ISSUE THREAD

**Issue by Owyn** [BGforgeNet/Fallout2_Restoration_Project#189]
### What happened
dude doesn't want to turn off turrets which gonna kill him in few sec

### What you expected to happen
dude wanting to live

### Screenshot
![image](https://user-images.githubusercontent.com/1309656/218281690-6eca8fc1-3c0b-408b-aead-47e2d5a2d87c.png)

### Savegame
[SLOT16.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/10714763/SLOT16.zip)

**Comment by burner1024** [comment]
Not sure it ever did what you want. Try to find some sources.

**Comment by Owyn** [comment]
Hm, it looks like it was either bugged in original game or just straight-off cut content (which restoration project should restore IMHO)

Found basically this https://www.reddit.com/r/classicfallout/comments/7rssqp/fallout_2_had_a_disappointing_ending_and_its_all/ 

I think finding out about turning turrets hostile to Frank is supposed to require bigger hacking (science) skill than simply turning them off (but again, both require president pass anyway, and many ppl wish it didn't (at least for just turning off turrets))

**Comment by burner1024** [comment]
It seems that maintenance option never did anything.
I think it's a bug, so fixed in both UPU and RPU.

The option now works. Still, it's not a complete disable, just a temporary one, for 1-3 minutes. Then they are back on again.
The weird dialog wording is changed to just "back".
I also wanted to make turrets to animate "stand down" to indicate status visually, but can't quickly find how to do that.

**Comment by NovaRain** [comment]
> Key requirement means that this option requires either clearing president's level, or savescumming for pick pocket, and I don't like that choice.

The only way to get the presidential pass is to kill him, as the pass is in his right hand.
For turrets standing down, try `ANIM_fall_back` or `ANIM_fall_back_sf` (similar to brahmin).

**Comment by Owyn** [comment]
> as the pass is in his right hand.

Wasn't there a perk or something to steal things held in hands?

**Comment by NovaRain** [comment]
> > as the pass is in his right hand.
> 
> Wasn't there a perk or something to steal things held in hands?

No, there's none.
https://fallout.wiki/wiki/Fallout_2_Perks

**Comment by burner1024** [comment]
OK, I added animations.

Turns out the terminal can already be hacked. It's something killap [added](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/b4300a4a8753d77c5180a1e23525fb2c9aa04535/docs/up-changelog.txt#L606) to both UP and RP.
Problem is, both counter insurgency and maintenance are locked behind presidential passkey, and the whole hacking procedure implies fooling scanner into thinking you have the key. So it makes no sense to require different science level for this.
I think it would be good to decouple these options, but I don't feel like diving into that now. Will need a few more dialog lines and stuff. Maybe someone takes an interest in doing that.
