### ISSUE TITLE
Kitsune will replace her tag skill to Unarmed if she's equipped with power armor

### ISSUE THREAD

**Issue by DondeEstaTuHallPass** [BGforgeNet/Fallout2_Restoration_Project#286]
Similar to how Cassidy in vanilla game will replace his tag skill from Small Guns to Unarmed if he's equipped with power armor, so will Kitsune. This will prevent Kitsune from using her lockpick skill for the players even if hers is higher than players'.

**Comment by NovaRain** [comment]
Her skills will be tweaked to prevent tag skill change. Her Melee is always 10% less than Unarmed.
| Stage |   Unarmed    |   Lockpick   |
|-------|--------------|--------------|
| Base  | 128% -> 125% | 130% -> 135% |
| 1     | 138% -> 135% | 140% -> 145% |
| 2     | 148% -> 145% | 150% -> 155% |
| 3     | 158% -> 155% | 160% -> 165% |
| 4     | 168% -> 165% | 170% -> 175% |
| 5     | 173% -> 170% | 175% -> 180% |

Other EPA party members are left as they are because their tag skills don't have any practical impact.
