### ISSUE TITLE
Various Tidbits

### ISSUE THREAD

**Issue by Njawl** [BGforgeNet/Fallout2_Restoration_Project#46]
Hi, sorry about not responding to my previous issues. I was busy with other things.

The idea of this thread is to point out smaller flaws and such. Maybe even have it open for people to see if someone else have pointed it out. I'm aware some of these may just part of the original design but it doesn't hurt to mention it. All of these issues were experienced with the latest vanilla RP.

The people in the bar of Klamath don't like you even if you are idolized in town. Buying a round on all of them doesn't help either.

In Klamath I wasn't able to bring up who were mutilating the brahmin to the lady with that issue. I had talked to the brothers who were asking me to aid them but I promised not to tell anyone when I refused. I had also seen the brothers when defending Torr's brahmin. I guess the issue is that your character is holding his promise but it seems funny you can't break your promise for the greater good.

Again in Klamath, the guy who gives you the key so you can take a look at the rat issue offers to give you skills in Outdoorsman for a fee. If you haven't accepted and you deal with the rat problem you can't properly talk to him again. I'm aware this is just unfortunate as it's common for people to do that when you're idolized.

In Vault City, when the topic of drugs in Redding is the topic you can't mention your knowledge from The Den that New Reno is getting medicinal shipments from Vault City in which they use to make Jet. Kind of a big deal if they worry about their gold imports.

The drunken munk in the Abbey in charge of the garden have a line you can't ask again if you don't mention it right away. You need to have talked with his friend in New Reno first. The line is about his pal.

In the Raider's Hideout it's hard to give a good reason to Shadow Who Walks on why they would lie to him. The problem is that it's pretty obvious and you can't give one even with high intelligence and very high charisma. I was able to pull it off later when I had bumped charisma up to Heroic and had become a Ranger along with more info on the issue. I was still convincing him without mentioning any deeper specifics if I remember correctly. The Ranger badge helped in further convincements.

You can't star in a porno with the Kama Sutra perk. And being the heavy weight champion to boot. There may be logical conclusions to this such as the place heaving reached high standards but the perk name along with its description gives you a feeling you should suffice. They don't accept you with an agility of 6.

If your followers are waiting for you you can't trade items from them without giving them something equal or better in monetary value in return. If you try to steal from them they will attack you unlike if they were with you.

I suggest the car being transparent when you walk behind it similar to objects and buildings. If you drop items behind it you can't pick them up anymore. You can move the car and return on foot but that is tedious and I assume you lose the items if you did this in the wasteland.

The president and the vice president being immune to the virus sent through the ventilation system. It seems odd because they don't seem to use any protective equipment. This also beats the purpose of doing a "charisma win" as the president's card is very useful. That and giving the president a taste of his own medicine. According with the conversation you have with him it seems like an intentional way of killing him.

Some endings are bad even though you did a lot to prevent it. Take the raiders blossoming even if you have destroyed them in NCR and their hidden slave pen to the southwest of The Den. I understand why these endings happen though they may not be the most realistic.

Any martial arts fight you have in a ring is very prone to crashing. As I mentioned from my previous issue ther were files I couldn't find debug code to turn on. The one I could find and turn on wasn't enough. I haven't seen any log files with it on after a crash. I can however provide you with a bugged save. If you save during a match that savegame becomes bugged and will always crash before it's your turn again. You also have unarmed moves you don't normally have when you load it. I can provide it here if you wish.

I might remember more with time

**Comment by burner1024** [comment]
> The idea of this thread is to point out smaller flaws and such. Maybe even have it open for people to see if someone else have pointed it out. I'm aware some of these may just part of the original design but it doesn't hurt to mention it. All of these issues were experienced with the latest vanilla RP.

Sorry, but issue reporting is strictly for [reporting issues](https://github.com/BGforgeNet/Fallout2_Restoration_Project#reporting-issues) (...). They must be clearly described, in scope, and have all relevant info and saves necessary for reproduction.
For discussion, there's a [forum](https://forums.bgforge.net/viewforum.php?f=34).

**Comment by Njawl** [comment]
The word issue is broad enough to include my, well, issues and I would greatly appreciate if you could at least tell me if there's any topic you would like me to expand on. That and it would have been nice if you added a link to the forum over at the wiki. You see I don't know what's already known or not so gathering a lot of material only for it to be closed because it's already known/fixed/irrelevant would be a lot of wasted time. It's more effective to let me know if you need more material.

**Comment by burner1024** [comment]
> The word issue

Sorry, I don't understand what do you mean by this.

>  I would greatly appreciate if you could at least tell me if there's any topic you would like me to expand on.

Honestly, I just glanced over. You see, issues have a lifecycle. They are opened, evaluated, reproduced, and if everything checks out, changes are performed, and these changes are linked directly to the issue they address, then the issue is closed.
It's nigh impossible to keep track of each issue, when they are all dropped into a wall of text. That's why it's important to have each one reported separately, with a clear way to reproduce.

Crashing is definitely a bug, however vanilla RP crashes will not be investigated, only the latest RPU, because there's been too many changes already.

Another example, being unable to become a champion with Kama Sutra perk does seem strange, but there's nothing to even look at, until it's reproduced.

> That and it would have been nice if you added a link to the forum over at the wiki.

What wiki do you mean? There's a link to the forum here:
![Captura de pantalla de 2020-04-22 20-28-13](https://user-images.githubusercontent.com/1279852/79987607-d71c1b80-84d7-11ea-8fb5-0129212d2dae.png)

> You see I don't know what's already known or not so gathering a lot of material only for it to be closed because it's already known/fixed/irrelevant would be a lot of wasted time.

There are changelogs for [RPU](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/master/docs/changelog.md) and [UPU](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/docs/changelog.md), and you can search [closed issues](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues).

**Comment by Njawl** [comment]
My bad, you seemed a bit focused on the word

Alright, I can open several issues but it feels cluttered due to the amount of them and some of them are more open minded rather than being clear bugs.

I meant to say the studio seems too strict considering your perk and already being a boxing celebrity in town.

And yes, the link is there but it's a bit hidden and the page doesn't mention what is better suited for the forum rather than being posted here as an issue.

Anything you want me to post as a separate issue?

**Comment by burner1024** [comment]
> Alright, I can open several issues but it felt it would be cluttering due to the amount of them and some of them are more open minded rather than being clear bugs.

With each issue discussed separately, those that will be deemed "not bugs" will be closed with appropriate resolution and remain in issue history, searchable. If later anyone comes up with an evidence that they are actually bugs, they can be revisited.
Don't be afraid to separate them, that the purpose of issue system - to divide and conquer.

> And yes, the link is there but it's a bit hidden and the page doesn't mention what is better suited for the forum rather than being posted here as an issue.

You can suggest how to improve visibilty, and/or to spell it out more clearly (again, in a separate issue). Even better if you submit a pull request.

> Anything you want me to post as a separate issue?

You can post anything from the list, if you think it falls into scope, but please make sure to include a save and reproduction steps ("click here, say this", etc). The followers issue is definitely not a bug, because they aren't on your team. The president thing does seem strange, however it'll need to be investigated, I'm not sure if changing that will have side effects on other ways of completion.

**Comment by Njawl** [comment]
I'm aware the follower issue isn't a bug but it's almost like it. It shouldn't make a difference since they know you but I can see how it's like this for when someone haven't agreed to join you.

I'll post the more clear issues. Let me know if you're missing some. Your input is important. You're pulling the shots after all.
