### ISSUE TITLE
v18 EPA : Bringing sulik into the room with two blocked fans (fumes) causes him to endlessly complain that he is poisoned

### ISSUE THREAD

**Issue by Question2** [BGforgeNet/Fallout2_Restoration_Project#72]
Using v18 RPU with sfall v4.2.8.

[SLOT04.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5760192/SLOT04.zip)
[SLOT03.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5760193/SLOT03.zip)

Slot03 is before entering the room, slot04 is after entering the room. After clearing the fans and leaving the room, Sulik won't stop complaining that he is poisoned, but he takes no damage. Waiting several days makes no difference, he never stops saying that he is poisoned.

Not sure what is meant to happen here, but he should stop complaining about the poison when he is outside the room or when the fans are cleared.

**Comment by NovaRain** [comment]
Before sfall 4.2.8, poison-related script functions can only poison the player not other critters. killap added reactions about being poisoned/radiated for party members in both UP and RP, but obviously those reactions couldn't get triggered. Now it's possible to change the poison level for an NPC.

It's not really a problem in vanilla/UP because related scripts (e.g. radscorpion's critter script) check if target object is the player before running poison function, but some EPA scripts lack the check and apply poison directly. That's why you start getting party members complaining.

For now you can use [this global script](https://www.nma-fallout.com/threads/fo2-poison-glitch.219848/#post-4403368) to remove the poison from party members. One side note is the whole "poison damages the player over time" mechanism is implemented for the player only. That means you can't just wait till the poison level on party members drop to zero like yourself, though one can make a similar mechanism for party members with global scripts.

**Comment by Question2** [comment]
Thanks, that explains it.

**Comment by burner1024** [comment]
@NovaRain will a global script to with proper poison support be added to sfall distribution? Or it'll have to handled on per mod basis?

**Comment by NovaRain** [comment]
Dunno, it won't come from me.
For RPU I'd suggest just adding the target check like in vanilla script and be done with it, unless you really want to dig into various scripts of doctor NPCs to handle poison curing for party members.
